version: "3"

services:

  axs:
    build: "."
    # image: node:12.3-alpine
    # command: sh -c "ls -hal /home/node/app/node_modules && npm start"
    environment:
      - NODE_ENV=development
      - PORT=8003
    ports:
      - "8003:8003"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      # Need to read https://stackoverflow.com/questions/51097652/install-node-modules-inside-docker-container-and-synchronize-them-with-host
      - /home/node/app/node_modules
    